// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `QJournalProtocolPB.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <QJournalProtocolPB.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name = "isFormatted";

const ::std::string __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name = "getJournalState";

}

namespace
{

const char* __QJournalProtocolProtos__ServiceException_name = "QJournalProtocolProtos::ServiceException";

struct __F__QJournalProtocolProtos__ServiceException : public ::IceInternal::UserExceptionFactory
{
    virtual void
    createAndThrow(const ::std::string&)
    {
        throw ::QJournalProtocolProtos::ServiceException();
    }
};

class __F__QJournalProtocolProtos__ServiceException__Init
{
public:

    __F__QJournalProtocolProtos__ServiceException__Init()
    {
        ::IceInternal::factoryTable->addExceptionFactory("::QJournalProtocolProtos::ServiceException", new __F__QJournalProtocolProtos__ServiceException);
    }

    ~__F__QJournalProtocolProtos__ServiceException__Init()
    {
        ::IceInternal::factoryTable->removeExceptionFactory("::QJournalProtocolProtos::ServiceException");
    }
};

const __F__QJournalProtocolProtos__ServiceException__Init __F__QJournalProtocolProtos__ServiceException__i;

}

QJournalProtocolProtos::ServiceException::ServiceException(const ::std::string& __ice_reason) :
    ::Ice::UserException(),
    reason(__ice_reason)
{
}

QJournalProtocolProtos::ServiceException::~ServiceException() throw()
{
}

::std::string
QJournalProtocolProtos::ServiceException::ice_name() const
{
    return __QJournalProtocolProtos__ServiceException_name;
}

QJournalProtocolProtos::ServiceException*
QJournalProtocolProtos::ServiceException::ice_clone() const
{
    return new ServiceException(*this);
}

void
QJournalProtocolProtos::ServiceException::ice_throw() const
{
    throw *this;
}

void
QJournalProtocolProtos::ServiceException::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice("::QJournalProtocolProtos::ServiceException", -1, true);
    __os->write(reason);
    __os->endWriteSlice();
}

void
QJournalProtocolProtos::ServiceException::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->read(reason);
    __is->endReadSlice();
}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::QJournalProtocolProtos::upCast(::IceProxy::QJournalProtocolProtos::QJournalProtocolPB* p) { return p; }

void
::IceProxy::QJournalProtocolProtos::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::QJournalProtocolProtos::QJournalProtocolPB>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::QJournalProtocolProtos::QJournalProtocolPB;
        v->__copyFrom(proxy);
    }
}

::QJournalProtocolProtos::IsFormattedResponseProto
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB* __del = dynamic_cast< ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB*>(__delBase.get());
            return __del->isFormatted(request, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name, __del, __cookie);
    try
    {
        __result->__prepare(__QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::QJournalProtocolProtos::IsFormattedResponseProto
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::end_isFormatted(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name);
    ::QJournalProtocolProtos::IsFormattedResponseProto __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::QJournalProtocolProtos::ServiceException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::QJournalProtocolProtos::GetJournalStateResponseProto
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB* __del = dynamic_cast< ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB*>(__delBase.get());
            return __del->getJournalState(request, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name, __del, __cookie);
    try
    {
        __result->__prepare(__QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::QJournalProtocolProtos::GetJournalStateResponseProto
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::end_getJournalState(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name);
    ::QJournalProtocolProtos::GetJournalStateResponseProto __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::QJournalProtocolProtos::ServiceException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::ice_staticId()
{
    return ::QJournalProtocolProtos::QJournalProtocolPB::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::QJournalProtocolProtos::QJournalProtocolPB);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::QJournalProtocolProtos::QJournalProtocolPB);
}

::IceProxy::Ice::Object*
IceProxy::QJournalProtocolProtos::QJournalProtocolPB::__newInstance() const
{
    return new QJournalProtocolPB;
}

::QJournalProtocolProtos::IsFormattedResponseProto
IceDelegateM::QJournalProtocolProtos::QJournalProtocolPB::isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::QJournalProtocolProtos::IsFormattedResponseProto __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::QJournalProtocolProtos::ServiceException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::QJournalProtocolProtos::GetJournalStateResponseProto
IceDelegateM::QJournalProtocolProtos::QJournalProtocolPB::getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::QJournalProtocolProtos::GetJournalStateResponseProto __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::QJournalProtocolProtos::ServiceException&)
            {
                throw;
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::QJournalProtocolProtos::IsFormattedResponseProto
IceDelegateD::QJournalProtocolProtos::QJournalProtocolPB::isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::QJournalProtocolProtos::IsFormattedResponseProto& __result, const ::QJournalProtocolProtos::IsFormattedRequestProto& __p_request, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_request(__p_request)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::QJournalProtocolProtos::QJournalProtocolPB* servant = dynamic_cast< ::QJournalProtocolProtos::QJournalProtocolPB*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->isFormatted(_m_request, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::QJournalProtocolProtos::IsFormattedResponseProto& _result;
        const ::QJournalProtocolProtos::IsFormattedRequestProto& _m_request;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __QJournalProtocolProtos__QJournalProtocolPB__isFormatted_name, ::Ice::Normal, __context);
    ::QJournalProtocolProtos::IsFormattedResponseProto __result;
    try
    {
        _DirectI __direct(__result, request, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::QJournalProtocolProtos::ServiceException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::QJournalProtocolProtos::GetJournalStateResponseProto
IceDelegateD::QJournalProtocolProtos::QJournalProtocolPB::getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::QJournalProtocolProtos::GetJournalStateResponseProto& __result, const ::QJournalProtocolProtos::GetJournalStateRequestProto& __p_request, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_request(__p_request)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::QJournalProtocolProtos::QJournalProtocolPB* servant = dynamic_cast< ::QJournalProtocolProtos::QJournalProtocolPB*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            try
            {
                _result = servant->getJournalState(_m_request, _current);
                return ::Ice::DispatchOK;
            }
            catch(const ::Ice::UserException& __ex)
            {
                setUserException(__ex);
                return ::Ice::DispatchUserException;
            }
        }
        
    private:
        
        ::QJournalProtocolProtos::GetJournalStateResponseProto& _result;
        const ::QJournalProtocolProtos::GetJournalStateRequestProto& _m_request;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __QJournalProtocolProtos__QJournalProtocolPB__getJournalState_name, ::Ice::Normal, __context);
    ::QJournalProtocolProtos::GetJournalStateResponseProto __result;
    try
    {
        _DirectI __direct(__result, request, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::QJournalProtocolProtos::ServiceException&)
    {
        throw;
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* QJournalProtocolProtos::upCast(::QJournalProtocolProtos::QJournalProtocolPB* p) { return p; }

namespace
{
const ::std::string __QJournalProtocolProtos__QJournalProtocolPB_ids[2] =
{
    "::Ice::Object",
    "::QJournalProtocolProtos::QJournalProtocolPB"
};

}

bool
QJournalProtocolProtos::QJournalProtocolPB::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__QJournalProtocolProtos__QJournalProtocolPB_ids, __QJournalProtocolProtos__QJournalProtocolPB_ids + 2, _s);
}

::std::vector< ::std::string>
QJournalProtocolProtos::QJournalProtocolPB::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__QJournalProtocolProtos__QJournalProtocolPB_ids[0], &__QJournalProtocolProtos__QJournalProtocolPB_ids[2]);
}

const ::std::string&
QJournalProtocolProtos::QJournalProtocolPB::ice_id(const ::Ice::Current&) const
{
    return __QJournalProtocolProtos__QJournalProtocolPB_ids[1];
}

const ::std::string&
QJournalProtocolProtos::QJournalProtocolPB::ice_staticId()
{
    return __QJournalProtocolProtos__QJournalProtocolPB_ids[1];
}

::Ice::DispatchStatus
QJournalProtocolProtos::QJournalProtocolPB::___isFormatted(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::QJournalProtocolProtos::IsFormattedRequestProto request;
    __is->read(request);
    __inS.endReadParams();
    try
    {
        ::QJournalProtocolProtos::IsFormattedResponseProto __ret = isFormatted(request, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::QJournalProtocolProtos::ServiceException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

::Ice::DispatchStatus
QJournalProtocolProtos::QJournalProtocolPB::___getJournalState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::QJournalProtocolProtos::GetJournalStateRequestProto request;
    __is->read(request);
    __inS.endReadParams();
    try
    {
        ::QJournalProtocolProtos::GetJournalStateResponseProto __ret = getJournalState(request, __current);
        ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
        __os->write(__ret);
        __inS.__endWriteParams(true);
        return ::Ice::DispatchOK;
    }
    catch(const ::QJournalProtocolProtos::ServiceException& __ex)
    {
        __inS.__writeUserException(__ex, ::Ice::DefaultFormat);
    }
    return ::Ice::DispatchUserException;
}

namespace
{
const ::std::string __QJournalProtocolProtos__QJournalProtocolPB_all[] =
{
    "getJournalState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "isFormatted"
};

}

::Ice::DispatchStatus
QJournalProtocolProtos::QJournalProtocolPB::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__QJournalProtocolProtos__QJournalProtocolPB_all, __QJournalProtocolProtos__QJournalProtocolPB_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __QJournalProtocolProtos__QJournalProtocolPB_all)
    {
        case 0:
        {
            return ___getJournalState(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___isFormatted(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
QJournalProtocolProtos::QJournalProtocolPB::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
QJournalProtocolProtos::QJournalProtocolPB::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
QJournalProtocolProtos::__patch(QJournalProtocolPBPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::QJournalProtocolProtos::QJournalProtocolPBPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::QJournalProtocolProtos::QJournalProtocolPB::ice_staticId(), v);
    }
}
