// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `QJournalProtocolPB.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __QJournalProtocolPB_h__
#define __QJournalProtocolPB_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>
#include <QJournalProtocol.pb.h>
#include <src/StreamProtobuf.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace QJournalProtocolProtos
{

class QJournalProtocolPB;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::QJournalProtocolProtos::QJournalProtocolPB>&);
::IceProxy::Ice::Object* upCast(::IceProxy::QJournalProtocolProtos::QJournalProtocolPB*);

}

}

namespace QJournalProtocolProtos
{

class QJournalProtocolPB;
bool operator==(const QJournalProtocolPB&, const QJournalProtocolPB&);
bool operator<(const QJournalProtocolPB&, const QJournalProtocolPB&);
::Ice::Object* upCast(::QJournalProtocolProtos::QJournalProtocolPB*);
typedef ::IceInternal::Handle< ::QJournalProtocolProtos::QJournalProtocolPB> QJournalProtocolPBPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::QJournalProtocolProtos::QJournalProtocolPB> QJournalProtocolPBPrx;
void __patch(QJournalProtocolPBPtr&, const ::Ice::ObjectPtr&);

}

namespace QJournalProtocolProtos
{

typedef hadoop::hdfs::AcceptRecoveryRequestProto AcceptRecoveryRequestProto;

typedef hadoop::hdfs::AcceptRecoveryResponseProto AcceptRecoveryResponseProto;

typedef hadoop::hdfs::CanRollBackRequestProto CanRollBackRequestProto;

typedef hadoop::hdfs::CanRollBackResponseProto CanRollBackResponseProto;

typedef hadoop::hdfs::DiscardSegmentsRequestProto DiscardSegmentsRequestProto;

typedef hadoop::hdfs::DiscardSegmentsResponseProto DiscardSegmentsResponseProto;

typedef hadoop::hdfs::DoFinalizeRequestProto DoFinalizeRequestProto;

typedef hadoop::hdfs::DoFinalizeResponseProto DoFinalizeResponseProto;

typedef hadoop::hdfs::DoPreUpgradeRequestProto DoPreUpgradeRequestProto;

typedef hadoop::hdfs::DoPreUpgradeResponseProto DoPreUpgradeResponseProto;

typedef hadoop::hdfs::DoRollbackRequestProto DoRollbackRequestProto;

typedef hadoop::hdfs::DoRollbackResponseProto DoRollbackResponseProto;

typedef hadoop::hdfs::DoUpgradeRequestProto DoUpgradeRequestProto;

typedef hadoop::hdfs::DoUpgradeResponseProto DoUpgradeResponseProto;

typedef hadoop::hdfs::FinalizeLogSegmentRequestProto FinalizeLogSegmentRequestProto;

typedef hadoop::hdfs::FinalizeLogSegmentResponseProto FinalizeLogSegmentResponseProto;

typedef hadoop::hdfs::FormatRequestProto FormatRequestProto;

typedef hadoop::hdfs::FormatResponseProto FormatResponseProto;

typedef hadoop::hdfs::GetEditLogManifestRequestProto GetEditLogManifestRequestProto;

typedef hadoop::hdfs::GetEditLogManifestResponseProto GetEditLogManifestResponseProto;

typedef hadoop::hdfs::GetJournalCTimeRequestProto GetJournalCTimeRequestProto;

typedef hadoop::hdfs::GetJournalCTimeResponseProto GetJournalCTimeResponseProto;

typedef hadoop::hdfs::GetJournalStateRequestProto GetJournalStateRequestProto;

typedef hadoop::hdfs::GetJournalStateResponseProto GetJournalStateResponseProto;

typedef hadoop::hdfs::HeartbeatRequestProto HeartbeatRequestProto;

typedef hadoop::hdfs::HeartbeatResponseProto HeartbeatResponseProto;

typedef hadoop::hdfs::IsFormattedRequestProto IsFormattedRequestProto;

typedef hadoop::hdfs::IsFormattedResponseProto IsFormattedResponseProto;

typedef hadoop::hdfs::JournalRequestProto JournalRequestProto;

typedef hadoop::hdfs::JournalResponseProto JournalResponseProto;

typedef hadoop::hdfs::NewEpochRequestProto NewEpochRequestProto;

typedef hadoop::hdfs::NewEpochResponseProto NewEpochResponseProto;

typedef hadoop::hdfs::PrepareRecoveryRequestProto PrepareRecoveryRequestProto;

typedef hadoop::hdfs::PrepareRecoveryResponseProto PrepareRecoveryResponseProto;

typedef hadoop::hdfs::PurgeLogsRequestProto PurgeLogsRequestProto;

typedef hadoop::hdfs::PurgeLogsResponseProto PurgeLogsResponseProto;

typedef hadoop::hdfs::RemoteEditLogManifestProto RemoteEditLogManifestProto;

typedef hadoop::hdfs::RemoteEditLogProto RemoteEditLogProto;

typedef hadoop::hdfs::RequestInfoProto RequestInfoProto;

typedef hadoop::hdfs::SegmentStateProto SegmentStateProto;

typedef hadoop::hdfs::StartLogSegmentRequestProto StartLogSegmentRequestProto;

typedef hadoop::hdfs::StartLogSegmentResponseProto StartLogSegmentResponseProto;

class ServiceException : public ::Ice::UserException
{
public:

    ServiceException() {}
    explicit ServiceException(const ::std::string&);
    virtual ~ServiceException() throw();

    virtual ::std::string ice_name() const;
    virtual ServiceException* ice_clone() const;
    virtual void ice_throw() const;

    ::std::string reason;

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::UserException::__writeImpl;
    using ::Ice::UserException::__readImpl;
    #endif
};

static ServiceException __ServiceException_init;

}

namespace Ice
{
template<>
struct StreamableTraits< ::QJournalProtocolProtos::ServiceException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

}

namespace QJournalProtocolProtos
{

class Callback_QJournalProtocolPB_isFormatted_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QJournalProtocolPB_isFormatted_Base> Callback_QJournalProtocolPB_isFormattedPtr;

class Callback_QJournalProtocolPB_getJournalState_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_QJournalProtocolPB_getJournalState_Base> Callback_QJournalProtocolPB_getJournalStatePtr;

}

namespace IceProxy
{

namespace QJournalProtocolProtos
{

class QJournalProtocolPB : virtual public ::IceProxy::Ice::Object
{
public:

    ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request)
    {
        return isFormatted(request, 0);
    }
    ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx)
    {
        return isFormatted(request, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::IsFormattedResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_isFormatted(request, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_isFormatted(request, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::IsFormattedResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_isFormatted(request, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_isFormatted(request, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::IsFormattedResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::QJournalProtocolProtos::IsFormattedResponseProto&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
                ::QJournalProtocolProtos::IsFormattedResponseProto __ret;
                try
                {
                    __ret = __proxy->end_isFormatted(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::QJournalProtocolProtos::IsFormattedResponseProto&)> _response;
        };
        return begin_isFormatted(request, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request)
    {
        return begin_isFormatted(request, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx)
    {
        return begin_isFormatted(request, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isFormatted(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isFormatted(request, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::QJournalProtocolProtos::Callback_QJournalProtocolPB_isFormattedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isFormatted(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto& request, const ::Ice::Context& __ctx, const ::QJournalProtocolProtos::Callback_QJournalProtocolPB_isFormattedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_isFormatted(request, &__ctx, __del, __cookie);
    }

    ::QJournalProtocolProtos::IsFormattedResponseProto end_isFormatted(const ::Ice::AsyncResultPtr&);
    
private:

    ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request)
    {
        return getJournalState(request, 0);
    }
    ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx)
    {
        return getJournalState(request, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::GetJournalStateResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getJournalState(request, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getJournalState(request, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::GetJournalStateResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getJournalState(request, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getJournalState(request, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::QJournalProtocolProtos::GetJournalStateResponseProto&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::QJournalProtocolProtos::GetJournalStateResponseProto&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
                ::QJournalProtocolProtos::GetJournalStateResponseProto __ret;
                try
                {
                    __ret = __proxy->end_getJournalState(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::QJournalProtocolProtos::GetJournalStateResponseProto&)> _response;
        };
        return begin_getJournalState(request, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request)
    {
        return begin_getJournalState(request, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx)
    {
        return begin_getJournalState(request, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJournalState(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJournalState(request, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::QJournalProtocolProtos::Callback_QJournalProtocolPB_getJournalStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJournalState(request, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto& request, const ::Ice::Context& __ctx, const ::QJournalProtocolProtos::Callback_QJournalProtocolPB_getJournalStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJournalState(request, &__ctx, __del, __cookie);
    }

    ::QJournalProtocolProtos::GetJournalStateResponseProto end_getJournalState(const ::Ice::AsyncResultPtr&);
    
private:

    ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_secure(bool __secure) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_twoway() const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_oneway() const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_batchOneway() const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_datagram() const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_batchDatagram() const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_compress(bool __compress) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_timeout(int __timeout) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<QJournalProtocolPB> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<QJournalProtocolPB*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace QJournalProtocolProtos
{

class QJournalProtocolPB : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace QJournalProtocolProtos
{

class QJournalProtocolPB : virtual public ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB,
                           virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace QJournalProtocolProtos
{

class QJournalProtocolPB : virtual public ::IceDelegate::QJournalProtocolProtos::QJournalProtocolPB,
                           virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace QJournalProtocolProtos
{

class QJournalProtocolPB : virtual public ::Ice::Object
{
public:

    typedef QJournalProtocolPBPrx ProxyType;
    typedef QJournalProtocolPBPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::QJournalProtocolProtos::IsFormattedResponseProto isFormatted(const ::QJournalProtocolProtos::IsFormattedRequestProto&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___isFormatted(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::QJournalProtocolProtos::GetJournalStateResponseProto getJournalState(const ::QJournalProtocolProtos::GetJournalStateRequestProto&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getJournalState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const QJournalProtocolPB& l, const QJournalProtocolPB& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const QJournalProtocolPB& l, const QJournalProtocolPB& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace QJournalProtocolProtos
{

template<class T>
class CallbackNC_QJournalProtocolPB_isFormatted : public Callback_QJournalProtocolPB_isFormatted_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::QJournalProtocolProtos::IsFormattedResponseProto&);

    CallbackNC_QJournalProtocolPB_isFormatted(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
        ::QJournalProtocolProtos::IsFormattedResponseProto __ret;
        try
        {
            __ret = __proxy->end_isFormatted(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_QJournalProtocolPB_isFormattedPtr
newCallback_QJournalProtocolPB_isFormatted(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::QJournalProtocolProtos::IsFormattedResponseProto&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QJournalProtocolPB_isFormatted<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QJournalProtocolPB_isFormattedPtr
newCallback_QJournalProtocolPB_isFormatted(T* instance, void (T::*cb)(const ::QJournalProtocolProtos::IsFormattedResponseProto&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QJournalProtocolPB_isFormatted<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QJournalProtocolPB_isFormatted : public Callback_QJournalProtocolPB_isFormatted_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::QJournalProtocolProtos::IsFormattedResponseProto&, const CT&);

    Callback_QJournalProtocolPB_isFormatted(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
        ::QJournalProtocolProtos::IsFormattedResponseProto __ret;
        try
        {
            __ret = __proxy->end_isFormatted(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QJournalProtocolPB_isFormattedPtr
newCallback_QJournalProtocolPB_isFormatted(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::QJournalProtocolProtos::IsFormattedResponseProto&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QJournalProtocolPB_isFormatted<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QJournalProtocolPB_isFormattedPtr
newCallback_QJournalProtocolPB_isFormatted(T* instance, void (T::*cb)(const ::QJournalProtocolProtos::IsFormattedResponseProto&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QJournalProtocolPB_isFormatted<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_QJournalProtocolPB_getJournalState : public Callback_QJournalProtocolPB_getJournalState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&);

    CallbackNC_QJournalProtocolPB_getJournalState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
        ::QJournalProtocolProtos::GetJournalStateResponseProto __ret;
        try
        {
            __ret = __proxy->end_getJournalState(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_QJournalProtocolPB_getJournalStatePtr
newCallback_QJournalProtocolPB_getJournalState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QJournalProtocolPB_getJournalState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_QJournalProtocolPB_getJournalStatePtr
newCallback_QJournalProtocolPB_getJournalState(T* instance, void (T::*cb)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_QJournalProtocolPB_getJournalState<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_QJournalProtocolPB_getJournalState : public Callback_QJournalProtocolPB_getJournalState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&, const CT&);

    Callback_QJournalProtocolPB_getJournalState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::QJournalProtocolProtos::QJournalProtocolPBPrx __proxy = ::QJournalProtocolProtos::QJournalProtocolPBPrx::uncheckedCast(__result->getProxy());
        ::QJournalProtocolProtos::GetJournalStateResponseProto __ret;
        try
        {
            __ret = __proxy->end_getJournalState(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_QJournalProtocolPB_getJournalStatePtr
newCallback_QJournalProtocolPB_getJournalState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QJournalProtocolPB_getJournalState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_QJournalProtocolPB_getJournalStatePtr
newCallback_QJournalProtocolPB_getJournalState(T* instance, void (T::*cb)(const ::QJournalProtocolProtos::GetJournalStateResponseProto&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_QJournalProtocolPB_getJournalState<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
